import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TicketsList from "@/components/TicketList";
import { Box, Container, Grid, Typography } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {

  // const isUserLoggedIn = useLogin();

  // if (!isUserLoggedIn) return <div>
  //   No tienes una cuenta
  // </div>;


  return (
    <>
      <Head>
        <title>Split Mate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Box py={4}>
          <Typography variant="h3">Split Mate</Typography>
        </Box>
        <TicketsList />
      </Container>
    </>
  );
}
